[[getting-started]]
= Getting started

[partintro]
--
Interested in deploying applications to the cloud with complex rollouts, sophisticated notifications (Slack, Email, etc.)?
Then this document is for you. It will coach you on using this application to install Spinnaker.
--


[[getting-started-introducing-spring-cloud-spinnaker]]
== Introducing Spring Cloud Spinnaker

image::https://www.cloudfoundry.org/wp-content/uploads/2015/09/cf-cert-landscape-color.svg[width="300", float="right"]

http://spinnaker.io[Spinnaker] is a multi-cloud continuous deployment platform released by Netflix with contributions
from Pivotal, Google, Microsoft and others. *Spring Cloud Spinnaker* is an installation tool meant to gather all the
necessary information and use it to deploy Spinnaker's microservices into a
https://www.cloudfoundry.org/use/cloud-foundry-certified/[certified Cloud Foundry installation].

It installs the follow Spinnaker components:

.Spinnaker modules
[cols="1,3", options="header"]
|===
|Module | Purpose

| clouddriver
| Carries out all cloud-based operations, e.g. deploy, resize, destroy, etc.

| deck
| Frontend UI

| echo
| Sends messages out over various channels like Slack and email

| front50
| Manages long term and inflight data, e.g. pipeline definitions and currently running pipelines

| gate
| Gateway API between the frontend (deck) and the backend services

| igor
| Polls for CI job status, e.g. Jenkins and Travis

| orca
| Orchestration engine used for all operations and pipelines
|===

NOTE: Spinnaker has other modules, but they aren't needed for a Cloud Foundry setup. For example, there is a module dedicate
to wrapping JAR artifacts as http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html[Amazon AMIs], also known as "baking", but Cloud Foundry doesn't need baking.

== Before installing Spinnaker

Before you actually install Spinnaker, you must decide where it will run, i.e. pick an organization and space. You
also need the following services created as well:

* An instance of Redis in the same space. You will need the name of this service later on when you enter all your settings.


== Installing Spinnaker

Composed of Boot-based microservices, Spinnaker is highly customizable. However, instead of trying to get in and tune
ever single setting, Spring Cloud Spinnaker lets you pick several options from the web page, and sets those properties
for you.

To run it, you simply need the artifact pulled down from
https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-spinnaker/{spring-cloud-spinnaker-version}/spring-cloud-spinnaker-{spring-cloud-spinnaker-version}.jar[Artifactory].

You can either run it directly...

[source,subs="verbatim,attributes"]
----
$ java -jar spring-cloud-spinnaker-{spring-cloud-spinnaker-version}.jar
----

...or install it in your instance of Cloud Foundry...

[source,subs="verbatim,attributes"]
----
$ cf push spring-cloud-spinnaker -p spring-cloud-spinnaker-{spring-cloud-spinnaker-version}.jar
----

Once hosted, you can navigate to the site and configure your Spinnaker settings.

=== Settings

After installing Spring Cloud Spinnaker, whether locally or in PCF somewhere, you will be faced with a collection of
settings. This may look like a lot, but compared to ALL the options Spinnaker comes with, this is a vast simplification.

The settings are split into two parts: *Target* and *Settings*.

* *Target* describes information needed to essentially "cf push" all the Spinnaker modules into PCF.
* *Settings* is information used Spinnaker after installation for it to, in turn, install things on its own.

The following settings are needed to help install Spinnaker modules.

.Installation Settings
[cols="1,3", options="header"]
|===
| Setting | Purpose

| Target API
| URL for the API where Spinnaker will be installed (In PWS, it's https://api.run.pivotal.io)

| Target Organization
| Name of the organization you want Spinnaker installed in

| Target Space
| Name of the space you want Spinnaker installed in

| Target Email
| Email to log into CF and install Spinnaker

| Target Password
| Password to log into CF and install Spinnaker

| Namespace
| Optional suffix to apply to Spinnaker module names (*test* will yield *clouddriver-test*, etc.)
|===

The following information is used by Spinnaker after installation for it to, in turn, install and manage things.

.Operations Settings
[cols="1,3", options="header"]
|===
| Setting | Purpose

| Redis Service
| Name of the Redis service clouddriver, echo, front50, and orca must bind to

| Default Org
| Organization where Spinnaker will make deployments. This is pre-filled from *Target Organization* up above, but can be
overridden. (_Coming: Multiple organization support_)

| Default Space
| Space where Spinnaker will make deployments. This is pre-filled from *Target Space* up above, but can be
overridden. (_Coming: Multiple space support_)

| Primary Account API
| URL for the API where Spinnaker will make deployments. This is pre-filled from *Target API* up above, but can be
overridden.

| Primary Account Console
| URL for App Manager (In PWS, it's https://console.run.pivotal.io)

| Account Name
| Account name for Spinnaker to use when logging into PCF

| Account Password
| Account password for Spinnaker to use when logging into PCF

| Repository Name/Access Code
| If you are pulling deployment artifacts from an http-based repository, put your username. If s3, put your access code

NOTE: If your repository isn't secured, leave blank

| Repository Password/Secret Code
| If you are pulling deployment artifacts from an http-based repository, put your password. If s3, put your secret code

 NOTE: If your repository isn't secured, leave blank

| Spring Config Location
| Override path location of your own set of Spinnaker configuration files.

| Domain
| Domain that Spinnaker will be installed into

| Primary Account Name
| Name of the account linked to the primary space

| All Account Names
| List of account names Spinnaker will interact with (separated by commas). This is pre-filled from *Primary Account Name*,
but can be overridden.
|===

With your settings filled in, click on the Status tab.

=== Deploying

On the Status tab, you have the ability to check each module, or deal with them all.

. Click on *Deploy All*.
. Sit back and sip on a cup of coffee. This will take some time.

== Next Steps

After getting Spinnaker up and running, you should be able to access deck, the UI for Spinnaker, by visiting
https://deck.<your domain>
